### ISSUE TITLE
Include patch version in releases (ex. 0.21.0 instead of 0.21)

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/pkgmt#18]
Minor releases of ploomber are tagged 0.21 instead of 0.21.0. I think this trips up poetry when I run `poetry update` -- it doesn't update from let's say 0.16 to 0.21 like I'd expect.

**Comment by edublancas** [comment]
is there any reason why poetry would fail? I looked at https://semver.org/, and it indeed suggests that all versions should have all components, so maybe that's why?

**Comment by reesehopkins** [comment]
I'm not sure? I just noticed that ploomber seemed to be the only package
that didn't upgrade for minor releases. I'd have to manually change my
dependencies. I believe I even specified it as `ploomber^0.18.0` and it
wouldn't install 0.21 on updates.
