### ISSUE TITLE
Bug with URL format (with `_` and `.`)

### ISSUE THREAD

**Issue by RodolfoFerro** [ploomber/pkgmt#21]
As reported [here (#80)](https://github.com/ploomber/projects/pull/80), there's an error with the logic of identifying a URL format.

The particular error is the following:
```
*** templates/timeseries/tasks/section-4-modeling-hyperparameter-optimization-via-grid-search.py ***
(404) https://www.digitalocean.com/community/tutorials/a-guide-to-time-series-forecasting-with-arima-in-python-3._
*** templates/timeseries/arima-python.ipynb ***
(404) https://www.digitalocean.com/community/tutorials/a-guide-to-time-series-forecasting-with-arima-in-python-3._
```

As seen, the URL finishes before `._`, but these symbols are also identified as part of the URL. The original URL is the following: https://www.digitalocean.com/community/tutorials/a-guide-to-time-series-forecasting-with-arima-in-python-3 (which can be opened without any problem)

The error occurs because this link is part of MD documentation and the _cursive format using `_text_` is intended to be used_, so something like this was written:
```
_This method is based on the following post: https://www.digitalocean.com/community/tutorials/a-guide-to-time-series-forecasting-with-arima-in-python-3._
```

**Comment by edublancas** [comment]
at first, i thought this was an error on pkgmt, but `.` an `_` are valid URL values. I pasted this in my notes app and it had the same issue. I fixed this already by removing those two characters  - I'm unsure why they were there in the first place.
