### ISSUE TITLE
skip tests when only docs/ have been modified

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#47]
Often PRs only modify documentation (the top `doc/` directory) so there isn't a point in running the unit or integration tests, we should create a script that allows us to determine if a PR is exclusively modifying `doc/` and nothing else.

The API should work as follows

```sh
python -m pkgmt.ensure_modified --base-branch {BASE} --only {PATH}
```

For example, to check if the current branch only modified `doc/` with respect to the `main` branch, I can run:

```sh
python -m pkgmt.ensure_modified --base-branch main --only doc/
```

If the current branch has only modified `doc/` the command should finish with exit code 0, if files outside `doc/` have been modified, it should finish with exit code 1.

Inside Python, we can use `subprocess` to run `git` commands and find out. We already have a similar workflow that checks if [CHANGELOG.md has been modified](https://github.com/ploomber/contributing/blob/main/sample-github-workflows/changelog.yml) but the logic is written in bash, for this issue, we should write the logic in Python as it's easier to maintain. Sample git commands to determine the modified files can be found [here](https://github.com/ploomber/contributing/blob/d2004250dea96e06ab120db0e50cb315b19c3b78/sample-github-workflows/workflow-edits.yml#L35).

Note that we need to make a slight modification and add the `...` operator, since we're only interested in changes introduced by the current branch (not the ones introduced by the `BASE_BRANCH`:

```sh
git diff --exit-code "$BASE_BRANCH..." doc/
```

**Comment by edublancas** [comment]
TO DO:

- [ ] implement `python -m pkgmt.check_modified`
- [ ] add unit tests
- [ ] implement sample github workflow (you can test in the [dummy](https://github.com/ploomber/dummy) repository, ask @edublancas for edit access)
- [ ] open PR with the finished workflow to this repo https://github.com/ploomber/contributing

**Comment by mehtamohit013** [comment]
AC:
- Complete To-Do above

**Comment by edublancas** [comment]
I found out that github actions has a paths feature, I took a quick look at the docs and I don't think we can use it for this since it triggers a github if a pattern matches (in our case we want an exclusive condition: doc/ should be the only modified directory). but still worth taking a look: https://github.com/bqplot/bqplot/blob/ff9848d566cb479cb6800fb8901bf91fcc6c7939/.github/workflows/build.yml#L6
