### ISSUE TITLE
action to check if changelog has been modified

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#48]
(note that this is an extension of #47 so we need to fix that one first)

Often, contributors forget to edit the `CHANGELOG.md` when submitting pull requests, we need to create logic to automatically let them know to remind them.

```sh
python -m pkgmt.ensure_modified --base-branch main --include CHANGELOG.md
```

This should exit with code 0 if CHANGELOG.md has been modified (it's ok if other files have been modified too), and exit with code 1 if CHANGELOG.md has not been modified, along with a message saying that CHANGELOG.md has not been modified.

TO DO:

- [ ] implement changes to `python -m pkgmt.ensure_modified`
- [ ] add unit tests
- [ ] implement sample github workflow (you can test in the [dummy](https://github.com/ploomber/dummy) repository, ask @edublancas for edit access)
- [ ] open PR with the finished workflow to this repo https://github.com/ploomber/contributing and replace [this file](https://github.com/ploomber/contributing/blob/main/sample-github-workflows/changelog.yml)

**Comment by edublancas** [comment]
we can implement it in jupysql's CI. perhaps right after installation? i.e., if there is no new changelog entry, we don't even run the tests: https://github.com/ploomber/jupysql/blob/3ba79ab50852c81eca9d8764607fd1f8d5f36c02/.github/workflows/ci.yaml#L38

**Comment by mehtamohit013** [comment]
> we can implement it in jupysql's CI. perhaps right after installation? i.e., if there is no new changelog entry, we don't even run the tests: https://github.com/ploomber/jupysql/blob/3ba79ab50852c81eca9d8764607fd1f8d5f36c02/.github/workflows/ci.yaml#L38

@edublancas 
But some PR doesn't require a changelog, like my CI improvements one.
So, the ideal scenario would be to have a tag like `allow-workflow-edits`, here would be `no-changelog`, then we skip the changelog test

**Comment by edublancas** [comment]
good point! 

are you thinking of something like this?

so if there is no tag -> we fail the PR if it doesn't have a changelog entry
if there is a no-changelog tag -> we just continue with the tests

**Comment by mehtamohit013** [comment]
Yes

**Comment by edublancas** [comment]
sure, that works
