### ISSUE TITLE
clearer error message when unable to find root

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#54]
when missing a pyproject.toml, a "unable to find root" is displayed, but the reason of failure isn't displayed and no way to fix is suggested. see https://github.com/ploomber/sql/issues/11#issuecomment-1583392529

instead, we should display a message requesting the user to add a pyproject.toml file in the root folder: https://github.com/ploomber/pkgmt/blob/87d6f7507db590c490323599b414d682656a32ba/src/pkgmt/hook.py#L25

**Comment by tl3119** [comment]
Here is the PR for this issue: https://github.com/ploomber/pkgmt/pull/59

**Comment by edublancas** [comment]
forgot to mention that there are a few instances that need changes: https://github.com/search?q=repo%3Aploomber%2Fpkgmt+could+not+find&type=code

also, the use of `\` is discouraged, as it adds some weird whitespace:

```
Could not find project root.                     Please add a pyproject.toml file in the root folder
```

you can use parenthesis to break multi line strings. also please add some unit tests (you can see the test_cli.py) to get an idea

**Comment by tl3119** [comment]
It seems it already has the test to check whether it has pyproject.toml file in the root: https://github.com/ploomber/pkgmt/blob/87d6f7507db590c490323599b414d682656a32ba/tests/test_cli.py#LL52C1-L52C33
What's the purpose of the other tests we want to add?

**Comment by edublancas** [comment]
we should also have an instance where we call `pkgmt format`, the one you showed is testing  the git hook. please add it if it's missing so we have both cases

also, modify the test cases to check that the new error message appears (saying that pyproject.toml is missing)
