### ISSUE TITLE
Skip read-only directories and files when formatting and linting

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/pkgmt#55]
When running `pkgmt format` and `pkgmt lint`, sometimes the repository contains some read-only file ([encountered here](https://github.com/ploomber/core/pull/67)). In such a case `pkgmt` should skip that files with a warning and continue checking ahead.

Sample Traceback:
```
***black returned errors.***
PermissionError: [Errno 13] Permission denied: '/home/mohit/ploomber/core/stats/.gitignore'
```

**Comment by edublancas** [comment]
we're relying on black and nbqa for this, so we don't have on the files that get processed. one thing we can do is to check if black has any mechanism to skip read-only files.

**Comment by edublancas** [comment]
@mehtamohit013 can you check if there's any fix we can implement for this? Unsure if black supports a flag to ignore read-only files, so let's check and decide what we do

**Comment by mehtamohit013** [comment]
@edublancas 
I checked but `black` doesn't a feature like skip read-only files, but it does have an `--exclude` argument

**Comment by edublancas** [comment]
ok, so let's add the `--exclude`. `pkgmt lint` uses black and flake8, so we have to find the equivalent of `--exclude` in flake8. `pkgmt format` only uses black.

**Comment by mehtamohit013** [comment]
AC critera:
- Sweep the directory marking every file/dir as writable or not
- Pass the non-writable dir to `--exclude` command
- Changelog
- Testing
- Doc

**Comment by mehtamohit013** [comment]
Okay

**Comment by mehtamohit013** [comment]
@edublancas 
I have gone over the `cli` commands and just to confirm, we want to add a new argument `--exclude` to `lint`, `format`, `hook` in `pkgmt` `cli`?

**Comment by edublancas** [comment]
yes, we wanna add it to lint and format

we can leave hook out for now

**Comment by mehtamohit013** [comment]
A little Sidenote: users can also set the `exclude` argument in `pyproject.toml` for black ([sample config](https://github.com/psf/black/blob/main/pyproject.toml)). The same goes for `flake8` in `.flake8` file
