### ISSUE TITLE
Make lint to accept path

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/pkgmt#56]
Currently, `pkgmt lint` will apply the lint to the current folder

Let's have something like: `pkgmt lint path_to_folder`

**Comment by mehtamohit013** [comment]
AC Criteria
- Add a folder option to `pkgmt lint`
- Changelog
- Testcases

**Comment by tonykploomber** [comment]
Also, `pkgmt format` can have save feature when `lint` is done!
