### ISSUE TITLE
validate top keys in configuration file

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#65]
see test one here: https://github.com/ploomber/pkgmt/pull/60#pullrequestreview-1522649980

**Comment by neelasha23** [comment]
Please assign this to me @edublancas

**Comment by neelasha23** [comment]
Acceptance criteria:

1. Validate keys in `pyproject.toml` file and raise error if any invalid key found. Display all the valid keys to user.
2. Test cases for the same
3. Changelog entry.

**Comment by edublancas** [comment]
sounds good!
