### ISSUE TITLE
add `--version` to `pkgmt setup`

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#72]
should allow selecting a python version. the implementation is already there, we just have to modify the CLI

to test it, we can add a test to call the cli with --version and then mock the function and ensure it gets called with the right argument

**Comment by bryannho** [comment]
Verifying my approach to this issue - I will modify `pkgmt setup` in `cli.py` to include a "--version" flag. This will pass the necessary version to be used in `dev.py::setup()`. Then I will add a test to call `pkgmt setup --version X.XX` and ensure the function is called with the correct argument

**Comment by edublancas** [comment]
correct! the idea is that we should be able to choose a python version

**Comment by bryannho** [comment]
Is there a minimum python version that `pkgmt setup` should officially support? Or should the user be able to choose any python version, as long as the conda env can be created successfully? According to [this link](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html), Conda supports Python 3.8, 3.9, 3.10, and 3.11.

**Comment by edublancas** [comment]
we don't need to do any validation, we just forward the parameter to conda
